import "./globals.css"
import "@turbo-with-tailwind/design-system/styles.css"
import "@turbo-with-tailwind/ui/styles.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Turborepo with Tailwind",
  description: "Generated by create turbo with example with-tailwind.",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
